---
- name: Include tasks for specific OS
  include: '{{ ansible_system }}/{{ ansible_os_family }}.yml'

- name: Configure the consul firewall
  include: '{{ ansible_system }}/firewall.yml'

- name: Installation the HashiCorp consul
  include: '{{ ansible_system }}/install.yml'

- name: Configuration the consul
  include: '{{ ansible_system }}/configureation.yml'

- name: Reload the consul service
  shell: echo ''
  notify: 'Ensure consul service is enabled'
  when: consul_upgrade is changed or config_update is changed or systemd_update is changed or ssl_update is changed or acl_master_update is changed or acl_client_update is changed

- name: Installation the hashi-ui
  include: '{{ ansible_system }}/hashi-ui.yml'
  when:
    - consul_node_role == 'server'
    - consul_hashiui_is_install

- name: Reload the hashiui service
  shell: echo ''
  notify: 'Ensure hashiui service is enabled'
  when: 
    - consul_node_role == 'server'
    - consul_hashiui_is_install
    - hashiui_upgrade is changed or hashiui_systemd_update is changed

- name: Force the handler to run immediately
  meta: flush_handlers

- name: Installation the prometheus consul exporter
  include: '{{ ansible_system }}/exporter.yml'

- include_tasks: '{{ ansible_system }}/register.yml'
  when: consul_public_register
