---
- name: Include tasks for specific OS
  include: '{{ ansible_system }}/{{ ansible_os_family }}.yml'

- name: Configure the consul firewall
  include: '{{ ansible_system }}/firewall.yml'

- name: Installation the HashiCorp consul
  include: '{{ ansible_system }}/install.yml'

- name: Configuration the consul
  include: '{{ ansible_system }}/configureation.yml'

- name: Reload the consul service
  shell: echo ''
  notify: 'Ensure consul service is enabled'
  when: consul_upgrade is changed or config_update is changed or systemd_update is changed or ssl_update is changed

- name: Installation the hashi-ui
  include: '{{ ansible_system }}/hashi-ui.yml'
  when:
    - consul_node_role == 'server'
    - consul_hashiui_is_install | bool

- name: Reload the hashiui service
  shell: echo ''
  notify: 'Ensure hashiui service is enabled'
  when: 
    - consul_node_role == 'server'
    - consul_hashiui_is_install | bool
    - hashiui_upgrade is changed or hashiui_systemd_update is changed

- name: Force the handler to run immediately
  meta: flush_handlers

- name: Created policy.
  include: '{{ ansible_system }}/policy.yml'
  when:
    - consul_node_role == 'server'
    - consul_servers[0] in ansible_default_ipv4.address

- name: Inspact the default token.
  include: '{{ ansible_system }}/token.yml'
  when: consul_acl_arg.enabled | bool

- name: Consul master ACL policy file transfer
  template:
    src: 'master.json.j2'
    dest: '/etc/consul/consul.d/master.json'
    owner: '{{ consul_arg.user }}'
    group: '{{ consul_arg.user }}'
    mode: '0640'
  register: acl_master_update
  when:
    - consul_node_role == 'server'
    - consul_acl_arg.enabled | bool
  no_log: true

- name: Consul client ACL policy file transfer
  template:
    src: 'client.json.j2'
    dest: '/etc/consul/consul.d/client.json'
    owner: '{{ consul_arg.user }}'
    group: '{{ consul_arg.user }}'
    mode: '0640'
  register: acl_client_update
  when:
    - consul_node_role == 'client'
    - consul_acl_arg.enabled | bool
  no_log: true

- name: Reload the consul service for default token replace.
  shell: echo ''
  notify: 'Ensure consul service is enabled'
  when: acl_master_update is changed or acl_client_update is changed

- name: Force the handler to run immediately
  meta: flush_handlers

- name: Installation the prometheus consul exporter
  include: '{{ ansible_system }}/exporter.yml'
  when: exporter_is_install | bool

- name: Registered with HashiCorp Consul
  include: '{{ ansible_system }}/register.yml'
  when:
    - exporter_is_install | bool
    - consul_public_register | bool
