---
- name: Include tasks for specific OS.
  include: '{{ ansible_system }}/{{ ansible_os_family }}.yml'

- name: Configure the consul firewall.
  include: '{{ ansible_system }}/firewall.yml'

- name: Installation the HashiCorp consul.
  include: '{{ ansible_system }}/install.yml'

- name: Include certificate tasks.
  include: '{{ ansible_system }}/certificates.yml'
  when: ansible_system == 'Linux'

- name: Configuration the consul.
  include: '{{ ansible_system }}/configureation.yml'

- name: Installation the hashi-ui.
  include: '{{ ansible_system }}/hashi-ui.yml'
  when:
    - consul_node_role == 'server'
    - consul_hashiui_is_install | bool

#- name: Reload the hashiui service
#  shell: echo ''
#  notify: 'Ensure hashiui service is enabled'
#  when: 
#    - consul_node_role == 'server'
#    - consul_hashiui_is_install | bool
#    - hashiui_upgrade is changed or hashiui_systemd_update is changed

- name: Force the handler to run immediately.
  meta: flush_handlers

- name: Created policy.
  include: '{{ ansible_system }}/policy.yml'
  when: consul_acl_arg.enabled | bool

- name: Inspact the token.
  include: '{{ ansible_system }}/token.yml'
  when: consul_acl_arg.enabled | bool

- name: Consul master ACL policy file transfer.
  template:
    src: 'master.hcl.j2'
    dest: '/etc/consul.d/master.hcl'
    owner: 'consul'
    group: 'consul'
    mode: '0640'
  register: acl_master_update
  when:
    - consul_node_role == 'server'
    - consul_acl_arg.enabled | bool
  no_log: true
  notify:
    - Enable consul service.

- name: Consul client ACL policy file transfer.
  template:
    src: 'client.hcl.j2'
    dest: '/etc/consul.d/client.hcl'
    owner: 'consul'
    group: 'consul'
    mode: '0640'
  register: acl_client_update
  when:
    - consul_node_role == 'client'
    - consul_acl_arg.enabled | bool
  no_log: true
  notify:
    - Enable consul service.

- name: Force the handler to run immediately
  meta: flush_handlers

- name: Installation the prometheus consul exporter
  include: '{{ ansible_system }}/exporter.yml'
  when: exporter_is_install | bool

- name: Registered with HashiCorp Consul
  include: '{{ ansible_system }}/register.yml'
  when:
    - exporter_is_install | bool
    - consul_public_register | bool

- name: Include backup tasks
  include: '{{ ansible_system }}/backup.yml'
  when: ansible_system == 'Linux'
