---
- name: Include OS-specific variables.
  include_vars: '{{ ansible_distribution_file_variety }}.yml'
  when: ansible_system == "Linux"

- name: Include OS-specific variables.
  include_vars: 'Windows.yml'
  when: ansible_system == "Win32NT"

- name: Include specific operating system operations.
  include: '{{ ansible_system }}.yml'