---
- name: Installation the HashiCorp consul
  include: '{{ ansible_system }}/install.yml'

- name: Configure the consul firewall
  include: '{{ ansible_system }}/firewall.yml'

- name: Configuration the consul
  include: '{{ ansible_system }}/configureation.yml'

- include_tasks: '{{ ansible_system }}/register.yml'
  when: consul_public_register