---
- name: Include tasks for specific OS
  include: '{{ ansible_system }}/install.yml'

- name: Configure the consul firewall
  include: '{{ ansible_system }}/firewall.yml'

- name: Configuration the consul
  include: '{{ ansible_system }}/configureation.yml'
