---
- name: Installation the HashiCorp consul
  include: '{{ ansible_system }}/install.yml'

- name: Configure the consul firewall
  include: '{{ ansible_system }}/firewall.yml'

- name: Inspact the token.
  include: '{{ ansible_system }}/token.yml'
  when: consul_acl_arg.enabled | bool

- name: Configuration the consul
  include: '{{ ansible_system }}/configureation.yml'

- name: Installation the prometheus consul exporter
  include: '{{ ansible_system }}/exporter.yml'

- include_tasks: '{{ ansible_system }}/register.yml'
  when: consul_public_register | bool
