---
- name: Enable consul service.
  systemd:
    name: 'consul.service'
    enabled: 'yes'
    state: 'restarted'
    daemon_reload: 'yes'
  async: 1
  poll: 0

- name: Enable hashiui service.
  systemd:
    name: 'hashi-ui.service'
    enabled: 'no'
    state: 'restarted'
    daemon_reload: 'yes'
  async: 1
  poll: 0
  listen: Ensure hashiui service is enabled
