---
- name: Creating consul folder.
  file:
    dest: '{{ consul_path }}/{{ item.path }}'
    state: 'directory'
    owner: '{{ item.owner }}'
    group: '{{ item.owner }}'
    mode: '{{ item.mode }}'
  loop:
    - { path: 'backup', owner: 'root', mode: '0755' }
    - { path: 'backup/consul', owner: '{{ consul_arg.user }}', mode: '0755' }

- name: Creating Rclone configureation folder.
  file:
    dest: '/etc/rclone'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  when:
    - consul_backupset_arg.cloud_rsync | bool
    - consul_backupset_arg.cloud_drive is defined

- name: Rclone configuration file transfer.
  template:
    src: 'rclone.conf.j2'
    dest: '/etc/rclone/consul.conf'
    owner: '{{ consul_arg.user }}'
    group: '{{ consul_arg.user }}'
    mode: '640'
  when:
    - consul_backupset_arg.cloud_rsync | bool
    - consul_backupset_arg.cloud_drive is defined

- name: Consul backup scripts file transfer.
  template:
    src: 'consul_backup.sh.j2'
    dest: '/usr/local/bin/consul_backup.sh'
    owner: '{{ consul_arg.user }}'
    group: '{{ consul_arg.user }}'
    mode: '640'

- name : Consul backup job.
  cron:
    user: '{{ consul_arg.user }}'
    name: 'Consul Snapshot backup'
    minute: "{{ 60 | random(seed=inventory_hostname) }}"
    hour: "{{ 6 | random(seed=inventory_hostname,step=1) }}"
    job: '/bin/sh /usr/local/bin/consul_backup.sh'
  no_log: true
