---
- name: Check private key exists.
  stat:
    path: '/etc/consul/ssl/server.key'
  register: check_cert_keys

- name: Certificate Signing operation.
  block:
    - name: Selfsigned CA file transfer.
      copy:
        src: 'ssl/{{ item }}'
        dest: '/etc/consul/ssl/{{ item }}'
        owner: '{{ consul_arg.user }}'
        mode: '640'
      loop:
        - 'ca-cert.pem'
        - 'ca-key.pem'
    - name: Generate an OpenSSL private key.
      openssl_privatekey:
        path: '/etc/consul/ssl/server.key'
        select_crypto_backend: 'cryptography'
        size: '2048'
        type: 'RSA'
        owner: 'root'
        mode: '0644'
        state: 'present'
    - name: Generate an OpenSSL Certificate Signing Request.
      openssl_csr:
        path: '/etc/consul/ssl/server.csr'
        privatekey_path: '/etc/consul/ssl/server.key'
        select_crypto_backend: 'cryptography'
        common_name: 'Server'
        subject_alt_name:
          - 'DNS:{{ ansible_hostname }}'
          - 'DNS:{{ ansible_fqdn }}'
          - 'IP:{{ ansible_default_ipv4.address }}'
        owner: 'root'
        mode: '0644'
        state: 'present'
    - name: Generate an OpenSSL certificate signed with your own CA certificate.
      openssl_certificate:
        path: '/etc/consul/ssl/server.crt'
        csr_path: '/etc/consul/ssl/server.csr'
        ownca_path: '/etc/consul/ssl/ca-cert.pem'
        ownca_privatekey_path: '/etc/consul/ssl/ca-key.pem'
        select_crypto_backend: 'cryptography'
        ownca_not_after: '+7305d'
        provider: 'ownca'
        owner: 'root'
        mode: '0644'
        state: 'present'
  when: not check_cert_keys.stat.exists or check_cert_keys.stat.size == 0
