---
- name: Consul systemd configuration.
  lineinfile:
    state: 'present'
    dest: '/lib/systemd/system/consul.service'
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    insertafter: '\[Service\]'
  loop:
    - { regexp: '^RestartSec', line: 'RestartSec=30s' }
  notify:
    - Enable consul service.

- name: Consul configuration file transfer.
  template:
    src: 'consul.hcl.j2'
    dest: '/etc/consul.d/consul.hcl'
    owner: 'consul'
    group: 'consul'
    mode: '0640'
  register: config_update
  no_log: true
  notify:
    - Enable consul service.

- name: Consul master ACL policy file transfer.
  template:
    src: 'master.hcl.j2'
    dest: '/etc/consul.d/master.hcl'
    owner: 'consul'
    group: 'consul'
    mode: '0640'
  register: acl_master_update
  when:
    - consul_node_role == 'server'
    - consul_acl_arg.enabled | bool
  no_log: true

- name: Consul client ACL policy file transfer.
  template:
    src: 'client.hcl.j2'
    dest: '/etc/consul.d/client.hcl'
    owner: 'consul'
    group: 'consul'
    mode: '0640'
  register: acl_client_update
  when:
    - consul_node_role == 'client'
    - consul_acl_arg.enabled | bool
  no_log: true
