---
- name: Creating consul folder
  file:
    dest: '{{ item }}'
    state: 'directory'
    owner: '{{ consul_arg.user }}'
    group: '{{ consul_arg.user }}'
    mode: '0750'
  loop:
    - '/etc/consul'
    - '/etc/consul/consul.d'
    - '{{ consul_path }}/consul'
    - '{{ consul_path }}/backup/consul'

- name: Consul configuration file transfer
  template:
    src: 'config.json.j2'
    dest: '/etc/consul/config.json'
    owner: '{{ consul_arg.user }}'
    group: '{{ consul_arg.user }}'
    mode: '0640'
  register: config_update
  no_log: true

- name: Consul master ACL policy file transfer
  template:
    src: 'master.json.j2'
    dest: '/etc/consul/consul.d/master.json'
    owner: '{{ consul_arg.user }}'
    group: '{{ consul_arg.user }}'
    mode: '0640'
  register: acl_master_update
  when:
    - consul_node_role == 'server'
    - consul_acl_arg.enabled | bool
  no_log: true

- name: Consul client ACL policy file transfer
  template:
    src: 'client.json.j2'
    dest: '/etc/consul/consul.d/client.json'
    owner: '{{ consul_arg.user }}'
    group: '{{ consul_arg.user }}'
    mode: '0640'
  register: acl_client_update
  when:
    - consul_node_role == 'client'
    - consul_acl_arg.enabled | bool
  no_log: true

- name: Consul SSL certificate file transfer
  copy:
    src: 'ssl'
    dest: '/etc/consul'
    owner: '{{ consul_arg.user }}'
    group: '{{ consul_arg.user }}'
    mode: '0640'
  register: ssl_update
  no_log: true

- name: Consul systemd service file transfer
  template:
    src: 'consul.service.j2'
    dest: '/lib/systemd/system/consul.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: systemd_update

- name: Creating Rclone configureation folder.
  file:
    dest: '/etc/rclone'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  when:
    - consul_backupset_arg.cloud_rsync | bool
    - consul_backupset_arg.cloud_drive is defined

- name: Rclone configuration file transfer.
  template:
    src: 'rclone.conf.j2'
    dest: '/etc/rclone/consul.conf'
    owner: '{{ consul_arg.user }}'
    group: '{{ consul_arg.user }}'
    mode: '640'
  when:
    - consul_backupset_arg.cloud_rsync | bool
    - consul_backupset_arg.cloud_drive is defined

- name: Consul backup scripts file transfer.
  template:
    src: 'consul_backup.sh.j2'
    dest: '/usr/local/bin/consul_backup.sh'
    owner: '{{ consul_arg.user }}'
    group: '{{ consul_arg.user }}'
    mode: '640'

- name : Consul backup job.
  cron:
    user: '{{ consul_arg.user }}'
    name: 'Consul Snapshot backup'
    minute: "{{ 60 | random(seed=inventory_hostname) }}"
    hour: "{{ 6 | random(seed=inventory_hostname,step=1) }}"
    job: '/bin/sh /usr/local/bin/consul_backup.sh'
  no_log: true
