---
- name: Install the Consul Python dependencies packages.
  pip:
    name: '{{ item }}'
    state: 'present'
    extra_args: '--default-timeout=120 -i https://{{ consul_pypi_url }}/simple --trusted-host {{ consul_pypi_url }}'
  register: python_status
  loop: "{{ vars['consul_python_dependent_packages_' + ansible_distribution_major_version] }}"
  until: python_status is succeeded
  retries: 5
  delay: 2

- name: Creating consul folder.
  file:
    dest: '{{ item }}'
    state: 'directory'
    owner: 'consul'
    group: 'consul'
    mode: '0750'
  loop:
    - '/etc/consul.d/ssl'
    - '{{ consul_path }}/consul'
    - '/home/consul'
