---
- name: Install the Consul dependencies packages
  yum:
    name: '{{ item }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  with_items:
    - '{{ consul_dependent_packages }}'
