---
- name: Install the Consul dependencies packages
  yum:
    name: '{{ consul_dependent_packages }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  register: yum_status
  until: yum_status is succeeded
  retries: 3
  delay: 5