---
- name: Check exists token AccessorID
  uri:
    url: '{{ consul_public_http_prot }}://{{ consul_join_servers[0] }}:{{ consul_public_http_port }}/v1/acl/tokens'
    method: 'GET'
    timeout: '10'
    validate_certs: 'no'
    headers:
      X-Consul-Token: '{{ consul_acl_arg.master_token }}'
      X-Requested-By: '{{ ansible_default_ipv4.address }}'
      cache-control: 'no-cache'
  environment:
    no_proxy: '{{ consul_join_servers[0] }}'
  register: check_consul_token_accessorid
  until: check_consul_token_accessorid.status == 200
  retries: 5
  delay: 2
  no_log: true

- name: Check default Token
  uri:
    url: "{{ consul_public_http_prot }}://{{ consul_join_servers[0] }}:{{ consul_public_http_port }}/v1/acl/token/{{ item }}"
    method: 'GET'
    timeout: '10'
    validate_certs: 'no'
    headers:
      X-Consul-Token: '{{ consul_acl_arg.master_token }}'
      X-Requested-By: '{{ ansible_default_ipv4.address }}'
      cache-control: 'no-cache'
  environment:
    no_proxy: '{{ consul_join_servers[0] }}'
  loop: "{{ check_consul_token_accessorid | json_query('json[?Description==`An default token`].AccessorID') }}"
  changed_when: false
  failed_when: false
  no_log: true
  register: consul_default_token
  until: consul_default_token.status == 200
  retries: 5
  delay: 2

- name: Check agent Token
  uri:
    url: "{{ consul_public_http_prot }}://{{ consul_join_servers[0] }}:{{ consul_public_http_port }}/v1/acl/token/{{ item }}"
    method: 'GET'
    timeout: '10'
    validate_certs: 'no'
    headers:
      X-Consul-Token: '{{ consul_acl_arg.master_token }}'
      X-Requested-By: '{{ ansible_default_ipv4.address }}'
      cache-control: 'no-cache'
  environment:
    no_proxy: '{{ consul_join_servers[0] }}'
  loop: "{{ check_consul_token_accessorid | json_query(query) | flatten }}"
  vars:
    query: "json[?Description=='{{ ansible_hostname | upper }}-node'].AccessorID"
  no_log: true
  register: consul_agent_token
  until: consul_agent_token.status == 200
  retries: 5
  delay: 2
  when: consul_node_role == 'client'
