---
- name: Check if Consul exporter binary exists
  win_stat:
    path: 'c:\ProgramData\consul\bin\consul_exporter.exe'
  register: result

- name: Get Consul exporter
  win_copy:
    src: 'consul_exporter.zip'
    dest: 'c:\PROGRAMDATA\consul\consul_exporter.zip'
  when: not result.stat.exists

- name: Install consul exporter
  win_unzip:
    src: 'c:\PROGRAMDATA\consul\consul_exporter.zip'
    dest: 'c:\PROGRAMDATA\consul\bin'
    rm: 'yes'
  register: consul_exporter_upgrade
  when: not result.stat.exists

- name: Create Consul exporter service
  win_service:
    name: 'consul_exporter'
    path: 'start /b \"c:\ProgramData\consul\bin\consul_exporter.exe --web.listen-address=":{{ consul_port_arg.exporter }}" --consul.server="{% if consul_arg.https %}https{% else %}http{% endif %}://localhost:{{ consul_port_arg.http }}" --consul.health-summary\"'
    display_name: 'HashiCorp consul exporter'
    start_mode: 'auto'
    state: 'started'
    description: 'Consul exporter'
  when: consul_exporter_upgrade