---
- name: Check if Consul exporter binary exists
  win_stat:
    path: 'c:\ProgramData\consul\bin\consul_exporter.exe'
  register: result

- name: Get Consul exporter
  win_copy:
    src: 'consul_exporter.zip'
    dest: 'c:\PROGRAMDATA\consul\consul_exporter.zip'
  when: not result.stat.exists

- name: Install consul exporter
  win_unzip:
    src: 'c:\PROGRAMDATA\consul\consul_exporter.zip'
    dest: 'c:\PROGRAMDATA\consul\bin'
    rm: 'yes'
  register: consul_exporter_upgrade
  when: not result.stat.exists

- name: Install consul exporter script
  win_template:
    src: 'consul_exporter.bat'
    dest: 'c:\PROGRAMDATA\consul\bin\consul_exporter.bat'
  when: not result.stat.exists

- name: Startup Consul exporter
  win_command: 'c:\PROGRAMDATA\consul\bin\consul_exporter.bat'
  async: 1
  poll: 0
  when: not result.stat.exists

- name: Create a task to startup Consul exporter as boot
  win_scheduled_task:
    name: 'HashiCorp consul exporter'
    actions:
    - path: 'c:\PROGRAMDATA\consul\bin\consul_exporter.bat'
    state: present
    enabled: yes
    user: SYSTEM
    triggers:
    - type: 'boot'
