---
- name: Allow consul service TCP port
  win_firewall_rule:
    enable: yes
    state: present
    action: allow
    direction: In
    name: 'consul_{{ item.key }}'
    protocol: 'tcp'
    localport: '{{ item.value }}'
  with_dict:
    - '{{ consul_port_arg }}'

- name: Allow consul service UDP port
  win_firewall_rule:
    enable: yes
    state: present
    action: allow
    direction: In
    name: 'consul_UDP_{{ index }}'
    protocol: 'udp'
    localport: '{{ item }}'
  loop:
    - '{{ consul_port_arg.dns }}'
    - '{{ consul_port_arg.dns_interface }}'
    - '{{ consul_port_arg.serf_lan }}'
    - '{{ consul_port_arg.serf_wan }}'
  loop_control:
    index_var: index
