---
- name: Install chocolatey
  win_chocolatey:
    name: 'chocolatey'
    state: 'downgrade'
    version: '0.10.11'
    proxy_url: '{{ os_proxy_server | default(omit,true) }}'
  ignore_errors: yes

- name: 'Consul client installation'
  win_chocolatey:
    name: 'consul'
    state: 'latest'
    params: '-config-file="%PROGRAMDATA%\consul\config.json" -config-dir="%PROGRAMDATA%\consul\consul.d" -rejoin -ui -data-dir="%PROGRAMDATA%\consul\data"'
    timeout: '60'
    proxy_url: '{{ os_proxy_server | default(omit,true) }}'
  ignore_errors: yes
