---
- name: Creating consul folder
  win_file:
    path: 'c:\PROGRAMDATA\consul\{{ item }}'
    state: 'directory'
  loop:
    - 'bin'
    - 'consul.d'
    - 'logs'
    - 'data'

- name: Check current consul version
  win_command: 'c:\ProgramData\consul\bin\consul.exe --version'
  register: consul_current_version
  changed_when: false
  failed_when: false

- name: Stop current consul service
  win_service:
    name: 'consul'
    state: 'stopped'
  when:
    - consul_current_version.stdout is defined
    - consul_version not in consul_current_version.stdout

- name: Delete existing consul version if different
  win_file:
    path: 'c:\ProgramData\consul\bin\consul.exe'
    state: absent
  when:
    - consul_current_version.stdout is defined
    - consul_version not in consul_current_version.stdout
  register: consul_delete
  until: consul_delete is succeeded
  retries: 3
  delay: 5

- name: Get consul
  win_get_url:
    url: '{{ consul_soft_url }}/consul/{{ consul_version }}/consul_{{ consul_version }}_{{ ansible_os_family | lower }}_{{ consul_architecture[ansible_architecture] }}.zip'
    dest: 'c:\PROGRAMDATA\consul'
    proxy_url: '{{ os_proxy_server | default(omit,true) }}'
    timeout: 60
  when:
    - consul_current_version.rc == 2 or consul_version not in consul_current_version.stdout
  register: consul_download
  until: consul_download is succeeded
  retries: 3
  delay: 5

- name: Install consul
  win_unzip:
    src: 'c:\PROGRAMDATA\consul\consul_{{ consul_version }}_{{ ansible_os_family | lower }}_{{ consul_architecture[ansible_architecture] }}.zip'
    dest: 'c:\PROGRAMDATA\consul\bin'
    rm: 'yes'
  when:
    - consul_current_version.rc == 2 or consul_version not in consul_current_version.stdout
  register: consul_upgrade