---
- name: Register exporter service with an http health check
  win_uri:
    url: 'http://{{ item }}:{{ consul_public_http_port }}/v1/agent/service/register'
    method: 'PUT'
    body: '{"tags":["prometheus","exporter"],"ID":"{{ inventory_hostname | upper }}_consul_exporter","name":"consul_exporter","address":"{{ ansible_ip_addresses[0] }}","port":{{ consul_port_arg.exporter }},"meta":{"instance":"{{ inventory_hostname | upper }}","group":"{{ group_names[0] | upper }}","environment":"{{ environments | upper }}"},"checks":[{"http":"http://{{ ansible_ip_addresses[0] }}:{{ consul_port_arg.exporter }}/metrics","interval":"60s","tls_skip_verify":true,"method":"HEAD","timeout":"5s"}]}'
    body_format: 'json'
    status_code: '200'
    headers:
      X-Consul-Token: '{{ consul_public_exporter_token }}'
      X-Requested-By: '{{ ansible_ip_addresses[0] }}'
      cache-control: 'no-cache'
  environment:
    no_proxy: '{{ item }}'
  loop: '{{ consul_public_clients|flatten(levels=1) }}'
  register: register_status
  until: register_status.status_code == 200
  retries: 3
  delay: 3
  no_log: true
  changed_when: false
  failed_when: false
