---
- name: Check exists token AccessorID
  win_uri:
    url: '{{ consul_public_http_prot }}://{{ consul_join_servers[0] }}:{{ consul_public_http_port }}/v1/acl/tokens'
    method: 'GET'
    timeout: '10'
    validate_certs: 'no'
    headers:
      X-Consul-Token: '{{ consul_acl_arg.master_token }}'
      X-Requested-By: '{{ ansible_default_ipv4.address }}'
      cache-control: 'no-cache'
  environment:
    no_proxy: '{{ consul_join_servers[0] }}'
  changed_when: false
  failed_when: false
  no_log: true
  register: check_consul_token_accessorid

- name: Check default Token
  win_uri:
    url: "{{ consul_public_http_prot }}://{{ consul_join_servers[0] }}:{{ consul_public_http_port }}/v1/acl/token/{{ item }}"
    method: 'GET'
    timeout: '10'
    validate_certs: 'no'
    headers:
      X-Consul-Token: '{{ consul_acl_arg.master_token }}'
      X-Requested-By: '{{ ansible_default_ipv4.address }}'
      cache-control: 'no-cache'
  environment:
    no_proxy: '{{ consul_join_servers[0] }}'
  loop: "{{ check_consul_token_accessorid | json_query('json[?Description==`An default token`].AccessorID') }}"
  changed_when: false
  failed_when: false
  no_log: true
  register: consul_default_token
  until: consul_default_token.status_code == 200
  retries: 2
  delay: 2

- name: Check agent Token
  win_uri:
    url: "{{ consul_public_http_prot }}://{{ consul_join_servers[0] }}:{{ consul_public_http_port }}/v1/acl/token/{{ item }}"
    method: 'GET'
    timeout: '10'
    validate_certs: 'no'
    headers:
      X-Consul-Token: '{{ consul_acl_arg.master_token }}'
      X-Requested-By: '{{ ansible_default_ipv4.address }}'
      cache-control: 'no-cache'
  environment:
    no_proxy: '{{ consul_join_servers[0] }}'
  loop: "{{ check_consul_token_accessorid | json_query('json[?Description==`An agent token`].AccessorID') }}"
  changed_when: false
  failed_when: false
  no_log: true
  register: consul_agent_token
  until: consul_agent_token.status_code == 200
  retries: 2
  delay: 2
